spring.application.name=paymentmanager

spring.datasource.url=jdbc:postgresql://localhost:5432/PaymentManager
spring.datasource.username=postgres
spring.datasource.password=17082002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
